DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user(
	user_id INT(10) PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(100) NOT NULL,
	cellphone VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(500) NOT NULL,
	gender VARCHAR(10),
	role_id INT(10) NOT NULL,
	id_card VARCHAR(100) NOT NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_date TIMESTAMP ON UPDATE CURRENT_TIMESTAMP DEFAULT NOW()
)ENGINE=INNODB CHARSET=utf8mb4 COMMENT='用户信息表';

DROP TABLE IF EXISTS sys_role;
CREATE TABLE sys_role(
	role_id INT(10) PRIMARY KEY AUTO_INCREMENT,
	role_name VARCHAR(100) NOT NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_date TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=INNODB CHARSET=utf8mb4 COMMENT='角色信息表';

DROP TABLE IF EXISTS sys_course;
CREATE TABLE sys_course(
	course_id INT(10) PRIMARY KEY AUTO_INCREMENT,
	course_name VARCHAR(100) NOT NULL,
	course_start DATE NOT NULL,
	course_end DATE NOT NULL
)ENGINE=INNODB CHARSET=utf8mb4 COMMENT='课程信息表';

DROP TABLE IF EXISTS sys_user_course;
CREATE TABLE sys_user_course(
	user_name VARCHAR(100) NOT NULL,
	course_name VARCHAR(100) NOT NULL,
	score DOUBLE DEFAULT 0
)ENGINE=INNODB CHARSET=utf8mb4 COMMENT='角色课程信息表';
